title: Faiz's Blog
author:
  name: Syed Faiz Reza Zaidi
  title: IIT aspirant 
  # email: thefuzz_25@icloud.com
description: > # this means to ignore newlines until "show_excerpts:"
  Syed Faiz Reza Zaidi | IIT aspirant | 1st year @ FIITJEE Narayanguda, Hyd

google-analytics: G-024QNHMS9W

date_format: "%b %-d, %Y"
permalink: /blog/:title/

# generate social links in footer
socials:
  twitter: athamxa
  github:  thefuzz25
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  instagram: hamxa.xaidi
  linkedin: syed-hamza-zaidi
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

  # GitLab instances
  # gitlab:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

exclude:
 - Dockerfile
 - LICENSE.txt
 - README.md
 - README
 - setup.sh
 - Gemfile
 - Gemfile.lock
 - [vendor]

plugins:
 - jekyll-feed
 - jekyll-seo-tag
